version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx/dev
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/api
    depends_on:
      - api
    restart: always
    container_name: dev_fullstack_nginx
  
  api:
    build:
      context: ./docker/api/dev
    volumes:
      - ./api:/var/www/api
    restart: always
    depends_on:
      - db
    container_name: dev_fullstack_api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 123456
    container_name: dev_fullstack_db

  app:
    build:
      context: ./
      dockerfile: ./docker/app/dev/Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./docker/app/dev/install.sh:/var/www/install.sh
    ports:
      - 7777:8080
    restart: always
    depends_on:
      - nginx
    working_dir: /var/www/app
    container_name: dev_fullstack_app
    entrypoint: ["/bin/sh", "/var/www/install.sh"]

  admin:
    build:
      context: ./
      dockerfile: ./docker/admin/dev/Dockerfile
    volumes:
      - ./admin:/var/www/admin
      - ./docker/admin/dev/install.sh:/var/www/install.sh:ro
    ports:
      - 7778:8080
    restart: always
    depends_on:
      - nginx
    working_dir: /var/www/admin
    container_name: dev_fullstack_admin
    entrypoint: ["/bin/sh", "/var/www/install.sh"]

volumes:
  mysql:

