version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx/dev
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/api
    depends_on:
      - api
    restart: always
    container_name: dev_fullstack_nginx
  
  api:
    build:
      context: ./docker/api/dev
    volumes:
      - ./api:/var/www/api
    restart: always
    depends_on:
      - db
    container_name: dev_fullstack_api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 123456
    container_name: dev_fullstack_db

  app:
    build:
      context: ./docker/app/dev
    volumes:
      - ./app:/var/www/app
    ports:
      - 7777:8080
    restart: always
    depends_on:
      - nginx
    container_name: dev_fullstack_app

  admin:
    build:
      context: ./docker/admin/dev
    volumes:
      - ./admin:/var/www/admin
    ports:
      - 7778:8080
    restart: always
    depends_on:
      - nginx
    container_name: dev_fullstack_admin

volumes:
  mysql:

