version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx/prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./api:/var/www/api
    depends_on:
      - api
    restart: always
  
  api:
    build:
      context: ./docker/api/prod
    volumes:
      - ./api:/var/www/api
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 123456

volumes:
  mysql:
