version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx/prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./api:/var/www/api
      - ./app:/var/www/app
      - ./admin:/var/www/admin
    depends_on:
      - api
    restart: always
    container_name: prod_fullstack_nginx
  
  api:
    build:
      context: ./docker/api/prod
    volumes:
      - ./api:/var/www/api
    restart: always
    depends_on:
      - db
    container_name: prod_fullstack_api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 123456
    container_name: prod_fullstack_db

  app:
    build:
      context: ./docker/app/prod
    volumes:
      - ./app:/var/www/app
    restart: always
    depends_on:
      - nginx
    container_name: prod_fullstack_app


  admin:
    build:
      context: ./docker/admin/prod
    volumes:
      - ./admin:/var/www/admin
    restart: always
    depends_on:
      - nginx
    container_name: prod_fullstack_admin

volumes:
  mysql:
